"""Earth/Moon translational dynamics, force models, gravity, and integration."""

from lunarops.classes.ephemerides.body_ids import BodyId

from .bodies import BodyRole, DynamicalBody, ExternalStateProvider
from .context import AccelerationBatch, AccelerationBreakdown, DynamicsContext, HistoryProvider, PreparedEpoch
from .earth_moon import EarthMoonDynamics, FrameProviders
from .earth_orientation import (
    DE440_EARTH_POLE_OFFSET_X_ARCSEC,
    DE440_EARTH_POLE_OFFSET_Y_ARCSEC,
    de440_earth_dynamics_frame,
    de440_earth_pole_inertial,
)
from .force_models import (
    EarthTideForce,
    EihForce,
    FigureForce,
    ForceGroup,
    ForceModel,
    LenseThirringForce,
    LunarInertiaFigureForce,
    PointMassForce,
    SolarJ2Force,
    SolarRadiationPressureForce,
)
from .forces import (
    EarthTideModel,
    EarthTideParameters,
    NewtonianPointMassEvaluation,
    PreparedPointMassSystem,
    SolarForceParameters,
    eih_acceleration,
    evaluate_point_mass_system,
    extended_body_pair_accelerations,
    point_mass_acceleration,
    prepare_point_mass_system,
    solar_lense_thirring_acceleration,
    solar_radiation_pressure_acceleration,
)
from .gravity import (
    GravityField,
    as_gravity_field,
    frame_from_pole,
    load_gravity_coefficients,
    make_gravity_coefficients,
    make_j2_coefficients,
)
from .inertia import LunarInertiaModel, LunarInertiaParameters, degree2_from_inertia
from .integrators import (
    AdamsBashforthMoultonIntegrator,
    DynamicsSystem,
    GaussJacksonIntegrator,
    Integrator,
    IntegratorSettings,
    RegularTrajectory,
    RKNIntegrator,
    RungeKuttaIntegrator,
    StoermerCowellIntegrator,
)
from .state import CartesianState, EarthMoonBarycentricState, EarthMoonIntegrationState

__all__ = [
    "AccelerationBatch",
    "AccelerationBreakdown",
    "AdamsBashforthMoultonIntegrator",
    "BodyId",
    "BodyRole",
    "CartesianState",
    "DynamicalBody",
    "DynamicsContext",
    "DynamicsSystem",
    "EarthMoonBarycentricState",
    "EarthMoonDynamics",
    "DE440_EARTH_POLE_OFFSET_X_ARCSEC",
    "DE440_EARTH_POLE_OFFSET_Y_ARCSEC",
    "EarthMoonIntegrationState",
    "EarthTideForce",
    "EarthTideModel",
    "EarthTideParameters",
    "EihForce",
    "ExternalStateProvider",
    "FigureForce",
    "ForceGroup",
    "ForceModel",
    "FrameProviders",
    "de440_earth_dynamics_frame",
    "de440_earth_pole_inertial",
    "GaussJacksonIntegrator",
    "GravityField",
    "HistoryProvider",
    "Integrator",
    "IntegratorSettings",
    "LenseThirringForce",
    "LunarInertiaFigureForce",
    "LunarInertiaModel",
    "LunarInertiaParameters",
    "NewtonianPointMassEvaluation",
    "PointMassForce",
    "PreparedEpoch",
    "PreparedPointMassSystem",
    "RKNIntegrator",
    "RegularTrajectory",
    "RungeKuttaIntegrator",
    "SolarForceParameters",
    "SolarJ2Force",
    "SolarRadiationPressureForce",
    "StoermerCowellIntegrator",
    "as_gravity_field",
    "degree2_from_inertia",
    "eih_acceleration",
    "evaluate_point_mass_system",
    "extended_body_pair_accelerations",
    "frame_from_pole",
    "load_gravity_coefficients",
    "make_gravity_coefficients",
    "make_j2_coefficients",
    "point_mass_acceleration",
    "prepare_point_mass_system",
    "solar_lense_thirring_acceleration",
    "solar_radiation_pressure_acceleration",
]
